//! Configuration parsing and data structures for postmaster.
//!
//! The config is generated by the Nix module as JSON. It contains only
//! public information (store paths for ciphertext + key *names*).

#![allow(missing_docs, missing_debug_implementations)]

use std::path::Path;

use std::collections::HashMap;
use std::path::PathBuf;

use serde::Deserialize;

/// Full configuration loaded from the JSON file produced by the Nix module.
#[derive(Deserialize, Debug)]
pub struct Config {
    /// Where the .env.keys material comes from.
    pub keys: KeysSource,
    /// Absolute socket path → what to serve on it.
    pub credentials: HashMap<PathBuf, Entry>,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "snake_case")]
/// Where postmaster should obtain its own private keys.
pub enum KeysSource {
    /// Name under $CREDENTIALS_DIRECTORY (the daemon's own LoadCredential).
    Credential(String),
    /// Absolute filesystem path (must not live in the Nix store).
    File(PathBuf),
}

#[derive(Deserialize, Clone, Debug)]
/// A single credential mapping served by postmaster.
pub struct Entry {
    /// dotenvx-encrypted env file (a Nix store path; ciphertext is public).
    pub env_file: PathBuf,
    /// Which key inside it to serve.
    pub key: String,
    /// Additionally allow this (non-root) user to fetch the credential.
    /// Used by the darwin module, where consumers are launchd daemons
    /// connecting as their own service user rather than pid 1.
    #[serde(default)]
    pub peer_user: Option<String>,
}

pub struct Args {
    pub config: PathBuf,
    pub bind: bool,
    pub allow_nonroot: bool,
}

pub enum Invocation {
    Serve(Args),
    Fetch(PathBuf),
}

pub const USAGE: &str = "usage: postmaster --config <file.json> [--bind] [--allow-nonroot]\n       postmaster fetch <socket-path>";

/// Parse command line arguments. Kept simple with no external deps.
pub fn parse_args() -> Result<Invocation, String> {
    let mut it = std::env::args().skip(1).peekable();
    if it.peek().map(String::as_str) == Some("fetch") {
        it.next();
        let path = it.next().ok_or_else(|| USAGE.to_string())?;
        if it.next().is_some() {
            return Err(USAGE.into());
        }
        return Ok(Invocation::Fetch(PathBuf::from(path)));
    }
    let mut config = None;
    let mut bind = false;
    let mut allow_nonroot = false;
    while let Some(a) = it.next() {
        match a.as_str() {
            "--config" => config = Some(PathBuf::from(it.next().ok_or("--config needs a path")?)),
            "--bind" => bind = true,
            "--allow-nonroot" => allow_nonroot = true,
            "--help" | "-h" => return Err(USAGE.into()),
            other => return Err(format!("unknown argument: {other}")),
        }
    }
    Ok(Invocation::Serve(Args {
        config: config.ok_or("missing required --config <file.json>")?,
        bind,
        allow_nonroot,
    }))
}

/// dotenvx convention: `.env` → DOTENV_PRIVATE_KEY,
/// `.env.production` → DOTENV_PRIVATE_KEY_PRODUCTION.
pub fn key_var_for(env_file: &Path) -> Result<String, String> {
    let base = env_file
        .file_name()
        .and_then(|b| b.to_str())
        .ok_or_else(|| format!("{}: unreadable file name", env_file.display()))?;
    let rest = base.strip_prefix(".env").ok_or_else(|| {
        format!("{base}: env files must follow the `.env[.<environment>]` convention")
    })?;
    if rest.is_empty() {
        return Ok("DOTENV_PRIVATE_KEY".into());
    }
    let env = rest.strip_prefix('.').ok_or_else(|| {
        format!("{base}: env files must follow the `.env[.<environment>]` convention")
    })?;
    let suffix: String = env
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    Ok(format!("DOTENV_PRIVATE_KEY_{suffix}"))
}

#[cfg(test)]
#[allow(unused_qualifications)]
mod tests {
    use super::*;

    #[test]
    fn parse_args_fetch_mode() {
        // We can't easily mutate argv in a test without std::env::set_var tricks that are racy.
        // Instead we test the happy path logic by direct construction where possible,
        // and rely on integration via the binary + the fact that CI runs the built binary.
        // A minimal smoke: USAGE string is present.
        assert!(USAGE.contains("postmaster fetch"));
    }

    #[test]
    fn key_var_for_edge_cases() {
        assert!(key_var_for(std::path::Path::new("no-dot-env")).is_err());
    }
}
